#! /usr/bin/perl -w

# This is just a copy of another file so I remember how it goes.
# Most of this can probably be ripped out

use esmith::Build::CreateLinks qw(:all);
# my $event = "ipsec-update";

# ipsec-update

foreach (qw(
       /etc/printpdf.conf
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    remoteaccess-update
    ));
}

# Set up generic logfile timestamp renaming/symlinking

foreach (qw(
    /var/log/printpdf.log
    ))
{
    safe_touch "root/etc/e-smith/events/logrotate/logfiles2timestamp/$_";
}

#--------------------------------------------------
# actions for logrotate event
#--------------------------------------------------

# $event = "logrotate";

# safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ipsec");
